### ISSUE TITLE
Preset Layout for Bank of 4 Program Access Mode

### ISSUE THREAD

**Issue by sbmechanics** [griphiam/gcpeditor#10]
When in Bank of 4 mode (Configuration > Utility > Program Access Mode > Bank of 4), the presets section should be limited to 144 presets, in 26 banks (0-10, A-Z) with four presets each.

**Comment by markphilpot** [comment]
Hmm good point.  I'm assuming this is more tweak the UI for clarity rather than the .syx being ill formatted, since I believe it's an addressing issue only... The preset slots are the same. I'll see if I can tweak the rendering to render the right tabs on change.

**Comment by sbmechanics** [comment]
Does appear to be a UI tweak only based on which Program Access Mode (10 or 4) is active.  .syx is OK.

**Comment by markphilpot** [comment]
The "right" thing to do here is rip out my bad UI code and build it up with React components that will correctly manage the state change between modes... The `gcp.js` file would stay intact (thankfully) and this would involve refactoring `main.js`

**Comment by sbmechanics** [comment]
Is there a fire-breathing dragon label?
UI is aesthetically good - works well with Chrome (no good with MS Edge, but what is, so OK).
Drag and drop (for the non-CSV crowd) is likely a higher priority but would hook in.

**Comment by markphilpot** [comment]
A nice byproduct of moving to React would be that Drag-Drop would actually be easier to implement.  It's probably a two birds one stone sort of change.  I'll take a shot at this refactor in the next few weeks.

**Comment by sbmechanics** [comment]
Sounds like a good reason to merge the issues.  Thanks.

**Comment by sbmechanics** [comment]
Attempting temporary fix.
First steps:
main.js line 327 expanded bankLabels from 0-J to 0-Z
main.js line 343 changed from i/10 to i/NUM_PRESETS_PER_BANK

**Comment by sbmechanics** [comment]
Can render mode of 4 or mode of 10.  When mode is changed in config section, unable to re-render presets section without clearing data.

**Comment by markphilpot** [comment]
@sbmechanics Can you try out the the PR branch above and see if that hits all the edge cases? I think it does based on my testing, but a second opinion would be welcome.

**Comment by sbmechanics** [comment]
Looks really good, I believe it covers the bases.
SYX and CSV files, when in Bank of 4 mode, still have 200 presets, but I believe said approach is correct.  If I understand the device correctly, even when using Bank of 4 mode, 200 presets are still "in the device", but the last 56 are inaccessible on the pedal board, by design.
