### ISSUE TITLE
Program Change Receive Channel

### ISSUE THREAD

**Issue by clickcosmo** [griphiam/gcpeditor#6]
Works great so far. Only problem is that the "Program Change Receive Channel" box, shows +1 of what its supposed to. If the GCP is set to 11, the editor will show 12.

**Comment by sbmechanics** [comment]
Appears that changing list in index.html starting on line 216 will resolve.
Label in UI is wrong, syx is correct.
option value="x" should increment 1-16, not 0-15.

**Comment by markphilpot** [comment]
This is what that value is in the sysex spec:

`MIDI Channel: Range=0..15 (channels 1-16)`

The spec could be wrong.  The UI should definitely be 1..16, but looks like the sysex value should also be 1..16 rather than 0..15 like the spec says.

**Comment by sbmechanics** [comment]
Sysex values are transmitting correctly.  Only UI appears wrong.  
Correct code would likely be:

```
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
 <option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
```

Is the option value being modified to be -1 somewhere?

Test system works fine with code as above.

**Comment by markphilpot** [comment]
The integer in the `value=""` is the value that is written to the sysex file.  So:

`<option value="0">1</option>` means that we write 0 in the sysex file and the GCP should read that as responding on PC channel 1.

But it sounds like based on your testing if I change it to `<option value="1">1</option>`, the GCP reads that as responding on PC channel 1.  Is that right?

**Comment by sbmechanics** [comment]
Based on my testing, correct.  That would correspond with "2" showing up in the UI when channel 1 is actually in the sysex / GCP.  Spec is wrong?  DMC / Voodoo Labs implemented the receive spec incorrectly?

**Comment by markphilpot** [comment]
`shrug` -- just to double check, which version of the firmware are you testing it with? Just want to confirm that a difference in firmware version would result in different behavior (which would suck)

**Comment by sbmechanics** [comment]
1.13, also tested with 1.13b.   Latest I could get from Voodoo Lab.  Have you dumped a sysex to the GCP on your end?

**Comment by markphilpot** [comment]
I need to re-setup my midi connections double check... I don't use the PC change feature so it was something I didn't test in my setup.  I'll put in a PR.  I have 1.13, so it just looks like their own spec doesn't match their implementation.  Not unheard of.

**Comment by markphilpot** [comment]
I also get the feeling midi is notorious for one off errors, given that some devices are 0 based and some are 1 based.

**Comment by sbmechanics** [comment]
I just triple checked - I think there is more to it.  I used the code I sent above, and that channels are right.  But the Respond to Program Change button appears not to be working.
Tested with channels 2 and 8.

**Comment by markphilpot** [comment]
hmmm that would indicate that the sysex value should be 0..15.  Can you generate two dumps for me?  On your GCP, set the PC to 1, dump it, and then set the PC to 5 and dump it again.  I'll send you a dropbox link if that works for you.

I'll open them up in a hex editor to see what the GCP itself is expecting for that value.

**Comment by markphilpot** [comment]
Dropbox link removed.

**Comment by sbmechanics** [comment]
Dropbox or email please.
Can confirm that the table set the channel correctly, but that PGM RECV OFF shows on the GCP when the box is checked in the UI, prior to downloading.

**Comment by markphilpot** [comment]
So that's worrying.  The PGM RECV OFF/ON is packed into a "Soft Options" byte.  It's a completely separate setting than the PC value.  They definitely should affect each other.

**Comment by sbmechanics** [comment]
Sent four files - Channels 1 and 5, PGM RCV ON and OFF.

**Comment by sbmechanics** [comment]
Just to clarify, when I see the button isn't working, attached is the UI button I am referencing.
![capture](https://cloud.githubusercontent.com/assets/9850246/23393592/c0db5bb2-fd38-11e6-9206-5eebf004303e.PNG)

**Comment by markphilpot** [comment]
Welp, it looks like it is expecting 1..16 and not what the spec says.

**Comment by markphilpot** [comment]
What's more disconcerting is that the soft options byte (byte 131) on first glance isn't what I was expecting.  Below is what the spec says about the soft options byte:

`X0XX000X where X=don’t care and 0 is used as follows:                                D1=Global Program ON(1)/OFF(0)                                                         D3,D2=Link Mode:NONE(00), MASTER(01), or SLAVE(10)                   D6=Respond to MIDI Program Change, ON(1)/OFF(0)`

**Comment by markphilpot** [comment]
No, I think the spec matches the hex dumps for byte 131:
01 == Global Program: ON, Link Mode: NONE, Respond to MIDI PC: OFF
41 == Global Program: ON, Link Mode: NONE, Respond to MIDI PC: ON

let me run some tests to figure out what the tool is generating.

**Comment by markphilpot** [comment]
Can you check your GCP to see what your Global Program and Link Mode values are?

**Comment by sbmechanics** [comment]
LINK NONE
GBL PGM ON

**Comment by markphilpot** [comment]
Yeah... So i think my parsing of the soft options byte is wrong, since when I load your sysex, it reports GBL PGM as OFF.

I'll write some tests and get back to you.  Thanks for the files BTW! Definitely helps.

**Comment by markphilpot** [comment]
Yeah, looks like I screwed up the edian

```js
var SoftOptions = function(){
    this.val = 0;

    this.PROG_MASK = 0x80;
    this.PROG_UMASK = 0x7F;
    this.PROG_SHIFT = 7;
    this.LINK_MASK = 0x30;
    this.LINK_UMASK = 0xCF;
    this.LINK_SHIFT = 4;
    this.RESPOND_MASK = 0x01;
    this.RESPOND_UMASK = 0xFE;
    this.RESPOND_SHIFT = 0;

};
```

I'll get a PR out tomorrow.

**Comment by sbmechanics** [comment]
Thank you.

**Comment by sbmechanics** [comment]
Appears to fix "Respond to Program Change", unsure on link mode (needs testing).  However, when loading a syx with byte 131 set to 41 or 01, Global Program shows "Off" in the GUI.

**Comment by sbmechanics** [comment]
Fix for Global Program (lines 261-263):
`this.PROG_MASK = 0x01; // 0000 0001`
`this.PROG_UMASK = 0xFE; // 1111 1110`
`this.PROG_SHIFT = 0;`

**Comment by markphilpot** [comment]
Ugh... Yeah, it means the spec is off again.  If the spec was right, then the byte would be 0x42 showing the Global Program as On.  Ok... I'll update the PR to reflect those changes.

Thanks for the test.  Sucks when the device and spec diverge =)

**Comment by sbmechanics** [comment]
Just did a bunch of testing - with Global Program revision above:
1) Program Change Receive Channel working
2) Respond to Program Change working
3) Global Program working
4) Link Mode - None and Master working, dump from GCPro as SLAVE shows none in UI.  Checking.

**Comment by sbmechanics** [comment]
With Program Change and Global Program off, and slave only on, byte is 08.  With master only on, byte is 04 (as opposed to 00 with everything off).

**Comment by markphilpot** [comment]
That matches the spec: w/ everything else off master only is 0x04 and slave should have been 0x08, so thankfully that checks out.  The `option` values for master and slave are 1 and 2 respectively, so that should have matched.

The LINK_MASK is incorrect.  Should be 0x0C rather than 0x06

**Comment by markphilpot** [comment]
Just pushed change.  Hopefully that fixes everything.

**Comment by sbmechanics** [comment]
I got thrown off because your comment after the link mask was correct, but the mask itself, as you said, was off.
I just ran the same set of tests after changing the mask and everything works on my test system.  Thanks.

**Comment by sbmechanics** [comment]
this.programChangeReceiveChannel on line 316 of gcp.js should be changed to 0x01 to set default Program Changed Receive channel to 1 (now shows blank in UI).

**Comment by markphilpot** [comment]
Created a new Issue for ^^
