### ISSUE TITLE
Presets CSV Export-Import Expression Pedal Bug

### ISSUE THREAD

**Issue by sbmechanics** [griphiam/gcpeditor#7]
When exporting to CSV and making no changes to expression pedal values, the import will change the values.

For example, export of presets with all expression pedals set to:

- Pedal 1 Device 1

- Pedal 1 MIDI Definition MIDI Controller 2

- Pedal 2 Device 1

- Pedal 2 MIDI Definition MIDI Controller 3

On import, without change to CSV, all expression pedals change to:

- Pedal 1 Device 1

- Pedal 1 MIDI Definition MIDI Controller 2

- Pedal 2 Device 5

- Pedal 2 MIDI Definition Pitchbend

**Comment by markphilpot** [comment]
Identified fix. Will test tonight and push to the site.
